import AppError from "../errors/AppError";

export default class CPFAlreadyExistsException extends AppError {
  constructor() {
    super("JÃ¡ existe um cadastrado com esse CPF", 409);
  }
}
